language: java
jdk:
  - oraclejdk7
before_install:
  - sudo apt-get install -y -q erlang
install: dialyzer --build_plt --apps erts kernel stdlib
script: mvn clean && mvn -Pit verify -Dinvoker.streamLogs=true
